In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

folder = Path("../output_csv")

input_file = folder / "residential_cleaned.csv"

df = pd.read_csv(input_file, low_memory=False)

df.head()

,ClosePrice,source_month,LivingArea,DaysOnMarket,LotSizeSquareFeet,YearBuilt,BathroomsTotalInteger,BedroomsTotal,GarageSpaces,Latitude,...,PostalCode_92584,PostalCode_92592,PostalCode_92596,PostalCode_93065,PostalCode_93446,PostalCode_93535,PostalCode_93536,PostalCode_93551,PostalCode_94513,PostalCode_Other
0,890000.0,202506,3000.0,181,9600.0,2021.0,3.0,3.0,2.0,34.264692,...,False,False,False,False,False,False,False,False,False,True
1,1876384.0,202506,1800.0,87,10400.0,1963.0,3.0,3.0,2.0,34.107983,...,False,False,False,False,False,False,False,False,False,True
2,4820000.0,202506,4270.0,0,22505.0,1980.0,6.0,6.0,3.0,37.567434,...,False,False,False,False,False,False,False,False,False,True
3,865000.0,202506,1442.0,0,4800.0,1985.0,2.0,3.0,2.0,33.906058,...,False,False,False,False,False,False,False,False,False,True
4,875000.0,202506,1086.0,0,5500.0,1953.0,1.0,3.0,4.0,37.705919,...,False,False,False,False,False,False,False,False,False,True

In [3]:
target = 'ClosePrice'
# Train/test split by most recent month
df['source_month'] = df['source_month'].astype(float).astype(int).astype(str)

months = sorted(df['source_month'].unique())

test_month = months[-1]

In [4]:
import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

target = "ClosePrice"

df["source_month"] = (
    df["source_month"]
    .astype(float)
    .astype(int)
    .astype(str)
)

months = sorted(df["source_month"].unique())
test_month = months[-1]

drop_cols = [target, "source_month"]

feature_cols = [
    col for col in df.columns
    if col not in drop_cols
]

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),
    "Random Forest": RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )
}

model_results = []

for X_window in [3, 6, 9, 12]:

    train_months = months[-(X_window + 1):-1]

    train_df = df[
        df["source_month"].isin(train_months)
    ].copy()

    test_df = df[
        df["source_month"] == test_month
    ].copy()

    X_train = train_df[feature_cols]
    y_train = train_df[target]

    X_test = test_df[feature_cols]
    y_test = test_df[target]

    for model_name, estimator in models.items():

        # Fresh copy of each estimator for every training window
        model = clone(estimator)

        model.fit(X_train, y_train)

        train_preds = model.predict(X_train)
        test_preds = model.predict(X_test)

        model_results.append({
            "model": model_name,
            "training_window_months": X_window,
            "train_months": ", ".join(train_months),
            "test_month": test_month,
            "train_rows": len(train_df),
            "test_rows": len(test_df),
            "feature_count": len(feature_cols),
            "train_r2": r2_score(
                y_train,
                train_preds
            ),
            "test_r2": r2_score(
                y_test,
                test_preds
            ),
            "mae": mean_absolute_error(
                y_test,
                test_preds
            ),
            "rmse": np.sqrt(
                mean_squared_error(
                    y_test,
                    test_preds
                )
            )
        })

comparison_df = pd.DataFrame(model_results)

comparison_df = comparison_df.sort_values(
    by="test_r2",
    ascending=False
).reset_index(drop=True)

comparison_df

,model,training_window_months,train_months,test_month,train_rows,test_rows,feature_count,train_r2,test_r2,mae,rmse
0,Linear Regression,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,129591,12793,200,0.014958,0.472322,572191.011960,1.116176e+06
1,Linear Regression,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,61429,12793,200,0.015931,0.468593,556753.222951,1.120113e+06
2,Linear Regression,3,"202603, 202604, 202605",202606,35089,12793,200,0.014623,0.468579,566923.592680,1.120128e+06
3,Linear Regression,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,94495,12793,200,0.009956,0.465947,560517.607724,1.122899e+06
4,Random Forest,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,129591,12793,200,0.841250,-6.433140,352407.493405,4.189231e+06
5,Random Forest,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,61429,12793,200,0.826959,-9.470706,351271.454259,4.972057e+06
6,Random Forest,3,"202603, 202604, 202605",202606,35089,12793,200,0.843456,-9.525622,381037.588263,4.985079e+06
7,Random Forest,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,94495,12793,200,0.835601,-15.224120,435740.536669,6.189117e+06
8,Decision Tree,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,129591,12793,200,0.999988,-18.097696,364507.844717,6.714886e+06
9,Decision Tree,3,"202603, 202604, 202605",202606,35089,12793,200,1.000000,-32.807832,465317.242103,8.934223e+06
10,Decision Tree,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,94495,12793,200,0.999986,-37.532127,424544.209418,9.538051e+06
11,Decision Tree,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,61429,12793,200,0.999968,-53.937929,504810.377430,1.138897e+07

In [5]:
# Find the best Linear Regression baseline
best_baseline_row = (
    comparison_df[
        comparison_df["model"] == "Linear Regression"
    ]
    .sort_values(
        by="test_r2",
        ascending=False
    )
    .iloc[0]
)

best_baseline_r2 = best_baseline_row["test_r2"]
best_baseline_window = best_baseline_row["training_window_months"]

print("Best baseline window:", best_baseline_window)
print(f"Best baseline test R²: {best_baseline_r2:.4f}")

Best baseline window: 12
Best baseline test R²: 0.4723

In [6]:
comparison_df["baseline_test_r2"] = best_baseline_r2

comparison_df["r2_change_from_baseline"] = (
    comparison_df["test_r2"]
    - comparison_df["baseline_test_r2"]
)

comparison_df.sort_values(
    by="test_r2",
    ascending=False
)

,model,training_window_months,train_months,test_month,train_rows,test_rows,feature_count,train_r2,test_r2,mae,rmse,baseline_test_r2,r2_change_from_baseline
0,Linear Regression,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,129591,12793,200,0.014958,0.472322,572191.011960,1.116176e+06,0.472322,0.000000
1,Linear Regression,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,61429,12793,200,0.015931,0.468593,556753.222951,1.120113e+06,0.472322,-0.003730
2,Linear Regression,3,"202603, 202604, 202605",202606,35089,12793,200,0.014623,0.468579,566923.592680,1.120128e+06,0.472322,-0.003743
3,Linear Regression,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,94495,12793,200,0.009956,0.465947,560517.607724,1.122899e+06,0.472322,-0.006376
4,Random Forest,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,129591,12793,200,0.841250,-6.433140,352407.493405,4.189231e+06,0.472322,-6.905463
5,Random Forest,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,61429,12793,200,0.826959,-9.470706,351271.454259,4.972057e+06,0.472322,-9.943028
6,Random Forest,3,"202603, 202604, 202605",202606,35089,12793,200,0.843456,-9.525622,381037.588263,4.985079e+06,0.472322,-9.997944
7,Random Forest,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,94495,12793,200,0.835601,-15.224120,435740.536669,6.189117e+06,0.472322,-15.696442
8,Decision Tree,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,129591,12793,200,0.999988,-18.097696,364507.844717,6.714886e+06,0.472322,-18.570018
9,Decision Tree,3,"202603, 202604, 202605",202606,35089,12793,200,1.000000,-32.807832,465317.242103,8.934223e+06,0.472322,-33.280154
10,Decision Tree,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,94495,12793,200,0.999986,-37.532127,424544.209418,9.538051e+06,0.472322,-38.004450
11,Decision Tree,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,61429,12793,200,0.999968,-53.937929,504810.377430,1.138897e+07,0.472322,-54.410251

In [7]:
comparison_df["beat_baseline"] = (
    comparison_df["test_r2"] > best_baseline_r2
)

comparison_df[
    [
        "model",
        "training_window_months",
        "test_r2",
        "baseline_test_r2",
        "r2_change_from_baseline",
        "beat_baseline"
    ]
].sort_values(
    by="test_r2",
    ascending=False
)

,model,training_window_months,test_r2,baseline_test_r2,r2_change_from_baseline,beat_baseline
0,Linear Regression,12,0.472322,0.472322,0.000000,False
1,Linear Regression,6,0.468593,0.472322,-0.003730,False
2,Linear Regression,3,0.468579,0.472322,-0.003743,False
3,Linear Regression,9,0.465947,0.472322,-0.006376,False
4,Random Forest,12,-6.433140,0.472322,-6.905463,False
5,Random Forest,6,-9.470706,0.472322,-9.943028,False
6,Random Forest,3,-9.525622,0.472322,-9.997944,False
7,Random Forest,9,-15.224120,0.472322,-15.696442,False
8,Decision Tree,12,-18.097696,0.472322,-18.570018,False
9,Decision Tree,3,-32.807832,0.472322,-33.280154,False
10,Decision Tree,9,-37.532127,0.472322,-38.004450,False
11,Decision Tree,6,-53.937929,0.472322,-54.410251,False

# week 6

In [8]:
df_engineered = df.copy()

# Convert source month into year and month components
df_engineered["sale_year"] = (
    df_engineered["source_month"]
    .str[:4]
    .astype(int)
)

df_engineered["sale_month_number"] = (
    df_engineered["source_month"]
    .str[4:6]
    .astype(int)
)

df_engineered["sale_quarter"] = (
    (df_engineered["sale_month_number"] - 1) // 3 + 1
)

# Cyclical month features
df_engineered["month_sin"] = np.sin(
    2 * np.pi * df_engineered["sale_month_number"] / 12
)

df_engineered["month_cos"] = np.cos(
    2 * np.pi * df_engineered["sale_month_number"] / 12
)

In [9]:
# property age features


if "YearBuilt" in df_engineered.columns:

    df_engineered["property_age"] = (
        df_engineered["sale_year"]
        - df_engineered["YearBuilt"]
    )

    # Remove impossible negative ages
    df_engineered.loc[
        df_engineered["property_age"] < 0,
        "property_age"
    ] = np.nan

    df_engineered["property_age_squared"] = (
        df_engineered["property_age"] ** 2
    )

    df_engineered["is_new_property"] = (
        df_engineered["property_age"] <= 5
    ).astype(int)

    df_engineered["is_old_property"] = (
        df_engineered["property_age"] >= 50
    ).astype(int)

In [10]:
# bedroom and bathroom features 

if (
    "BedroomsTotal" in df_engineered.columns
    and "BathroomsTotalInteger" in df_engineered.columns
):

    bedrooms = df_engineered["BedroomsTotal"]
    bathrooms = df_engineered["BathroomsTotalInteger"]

    df_engineered["bed_bath_ratio"] = (
        bedrooms
        / bathrooms.replace(0, np.nan)
    )

    df_engineered["bath_bed_ratio"] = (
        bathrooms
        / bedrooms.replace(0, np.nan)
    )

    df_engineered["total_bed_bath"] = (
        bedrooms + bathrooms
    )

    df_engineered["bed_bath_difference"] = (
        bedrooms - bathrooms
    )

    df_engineered["more_bathrooms_than_bedrooms"] = (
        bathrooms > bedrooms
    ).astype(int)

In [11]:
# living area features 

if "LivingArea" in df_engineered.columns:

    df_engineered["living_area_squared"] = (
        df_engineered["LivingArea"] ** 2
    )

    df_engineered["log_living_area"] = np.log1p(
        df_engineered["LivingArea"].clip(lower=0)
    )

    df_engineered["small_home_flag"] = (
        df_engineered["LivingArea"] < 1000
    ).astype(int)

    df_engineered["large_home_flag"] = (
        df_engineered["LivingArea"] > 3000
    ).astype(int)


if (
    "LivingArea" in df_engineered.columns
    and "BedroomsTotal" in df_engineered.columns
):

    df_engineered["living_area_per_bedroom"] = (
        df_engineered["LivingArea"]
        / df_engineered["BedroomsTotal"].replace(0, np.nan)
    )


if (
    "LivingArea" in df_engineered.columns
    and "BathroomsTotalInteger" in df_engineered.columns
):

    df_engineered["living_area_per_bathroom"] = (
        df_engineered["LivingArea"]
        / df_engineered[
            "BathroomsTotalInteger"
        ].replace(0, np.nan)
    )

In [12]:
# lot size features

if "LotSizeSquareFeet" in df_engineered.columns:

    df_engineered["log_lot_size"] = np.log1p(
        df_engineered[
            "LotSizeSquareFeet"
        ].clip(lower=0)
    )

    df_engineered["large_lot_flag"] = (
        df_engineered["LotSizeSquareFeet"] > 10000
    ).astype(int)

    df_engineered["small_lot_flag"] = (
        df_engineered["LotSizeSquareFeet"] < 3000
    ).astype(int)



if (
    "LotSizeSquareFeet" in df_engineered.columns
    and "LivingArea" in df_engineered.columns
):

    df_engineered["lot_to_living_ratio"] = (
        df_engineered["LotSizeSquareFeet"]
        / df_engineered["LivingArea"].replace(0, np.nan)
    )

    df_engineered["building_coverage_ratio"] = (
        df_engineered["LivingArea"]
        / df_engineered[
            "LotSizeSquareFeet"
        ].replace(0, np.nan)
    )

    df_engineered["unused_lot_area"] = (
        df_engineered["LotSizeSquareFeet"]
        - df_engineered["LivingArea"]
    )

In [13]:
# story features 

if "Stories" in df_engineered.columns:

    df_engineered["single_story_flag"] = (
        df_engineered["Stories"] == 1
    ).astype(int)

    df_engineered["multi_story_flag"] = (
        df_engineered["Stories"] > 1
    ).astype(int)


if "Stories" in df_engineered.columns:

    df_engineered["single_story_flag"] = (
        df_engineered["Stories"] == 1
    ).astype(int)

    df_engineered["multi_story_flag"] = (
        df_engineered["Stories"] > 1
    ).astype(int)

In [14]:
missing_indicator_columns = [
    "LivingArea",
    "LotSizeSquareFeet",
    "YearBuilt",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "AssociationFee",
    "Stories",
    "MainLevelBedrooms"
]

for column in missing_indicator_columns:

    if column in df_engineered.columns:

        df_engineered[
            f"{column}_missing"
        ] = (
            df_engineered[column]
            .isna()
            .astype(int)
        )

df_engineered["missing_feature_count"] = (
    df_engineered.isna().sum(axis=1)
)


# clean infinite values

df_engineered = df_engineered.replace(
    [np.inf, -np.inf],
    np.nan
)

In [15]:
# fill with medians 

numeric_columns = (
    df_engineered
    .select_dtypes(include=np.number)
    .columns
)

df_engineered[numeric_columns] = (
    df_engineered[numeric_columns]
    .fillna(
        df_engineered[numeric_columns].median()
    )
)

In [16]:
import geopandas as gpd


folder = Path("../output_csv")


school_district_file = (
    folder / "DistrictAreas2526_-284845464123469011.geojson"
)

school_districts = gpd.read_file(
    school_district_file
)

print("School district shape:", school_districts.shape)
print("Original CRS:", school_districts.crs)
print("Columns:", school_districts.columns.tolist())


district_name_column = "DistrictName"
district_type_column = "DistrictType"


# --------------------------------------------------
# 2. Inspect the actual DistrictType values
# --------------------------------------------------

print(
    school_districts[district_type_column]
    .value_counts(dropna=False)
)


# Clean the district type text
school_districts[district_type_column] = (
    school_districts[district_type_column]
    .astype("string")
    .str.strip()
)


# Keep only Unified School Districts.
# contains() is safer than == "Unified" because the value
# could be something like "Unified School District".
unified_districts = school_districts[
    school_districts[district_type_column]
    .str.contains(
        "Unified",
        case=False,
        na=False
    )
].copy()

print(
    "Unified district polygons:",
    len(unified_districts)
)

print(
    unified_districts[
        [
            district_name_column,
            district_type_column
        ]
    ].head()
)


if unified_districts.empty:
    raise ValueError(
        "No Unified districts were found. "
        "Review the DistrictType values printed above."
    )


# --------------------------------------------------
# 3. Standardize the district CRS
# --------------------------------------------------

# GeoJSON should normally use EPSG:4326, but this ensures
# that the polygons and property coordinates use the same CRS.
if unified_districts.crs is None:
    unified_districts = unified_districts.set_crs(
        "EPSG:4326"
    )
else:
    unified_districts = unified_districts.to_crs(
        "EPSG:4326"
    )


# Fix invalid polygon geometries if any exist
unified_districts["geometry"] = (
    unified_districts.geometry.make_valid()
)

unified_districts = unified_districts[
    unified_districts.geometry.notna()
    & ~unified_districts.geometry.is_empty
].copy()


# Only retain fields needed for the spatial join
district_layer = unified_districts[
    [
        district_name_column,
        district_type_column,
        "geometry"
    ]
].copy()


# --------------------------------------------------
# 4. Clean property coordinates
# --------------------------------------------------

df_engineered = df_engineered.copy()

# Preserve each property's original position
df_engineered["_row_id"] = np.arange(
    len(df_engineered)
)


# Convert coordinates from text to numeric values
df_engineered["Latitude"] = pd.to_numeric(
    df_engineered["Latitude"],
    errors="coerce"
)

df_engineered["Longitude"] = pd.to_numeric(
    df_engineered["Longitude"],
    errors="coerce"
)


# California's approximate coordinate range.
# This also catches accidentally reversed coordinates.
valid_coordinate_mask = (
    df_engineered["Latitude"].between(
        32,
        43
    )
    & df_engineered["Longitude"].between(
        -125,
        -113
    )
)

print(
    "Properties with valid California coordinates:",
    valid_coordinate_mask.sum()
)

print(
    "Properties with invalid or missing coordinates:",
    (~valid_coordinate_mask).sum()
)


# Helpful diagnostic
print(
    df_engineered.loc[
        valid_coordinate_mask,
        ["Latitude", "Longitude"]
    ].head()
)


properties_with_coordinates = (
    df_engineered.loc[
        valid_coordinate_mask
    ]
    .copy()
)

properties_without_coordinates = (
    df_engineered.loc[
        ~valid_coordinate_mask
    ]
    .copy()
)


# --------------------------------------------------
# 5. Convert properties into geographic points
# --------------------------------------------------

properties_gdf = gpd.GeoDataFrame(
    properties_with_coordinates,
    geometry=gpd.points_from_xy(
        properties_with_coordinates["Longitude"],
        properties_with_coordinates["Latitude"]
    ),
    crs="EPSG:4326"
)


# Both layers should now use EPSG:4326
print("Property CRS:", properties_gdf.crs)
print("District CRS:", district_layer.crs)


# --------------------------------------------------
# 6. Spatially join properties to Unified districts
# --------------------------------------------------

properties_joined = gpd.sjoin(
    properties_gdf,
    district_layer,
    how="left",
    predicate="intersects"
)


# A point should generally match only one Unified district.
# This prevents duplicate property rows if district polygons overlap.
properties_joined = (
    properties_joined
    .sort_values("_row_id")
    .drop_duplicates(
        subset="_row_id",
        keep="first"
    )
)


# Remove GeoPandas-only fields
properties_joined = properties_joined.drop(
    columns=[
        "geometry",
        "index_right"
    ],
    errors="ignore"
)


# --------------------------------------------------
# 7. Add missing district fields to invalid coordinates
# --------------------------------------------------

properties_without_coordinates[
    district_name_column
] = pd.NA

properties_without_coordinates[
    district_type_column
] = pd.NA


# --------------------------------------------------
# 8. Recombine and restore original order
# --------------------------------------------------

df_engineered = pd.concat(
    [
        properties_joined,
        properties_without_coordinates
    ],
    ignore_index=True
)

df_engineered = (
    df_engineered
    .sort_values("_row_id")
    .reset_index(drop=True)
)


df_engineered[
    "school_district_missing"
] = (
    df_engineered[district_name_column]
    .isna()
    .astype(int)
)


school_district_match_rate = (
    df_engineered[district_name_column]
    .notna()
    .mean()
)

valid_coordinate_match_rate = (
    df_engineered.loc[
        valid_coordinate_mask,
        district_name_column
    ]
    .notna()
    .mean()
)


print(
    f"Overall school district match rate: "
    f"{school_district_match_rate:.2%}"
)

print(
    f"Match rate among valid coordinates: "
    f"{valid_coordinate_match_rate:.2%}"
)

print(
    df_engineered[
        [
            "Latitude",
            "Longitude",
            district_name_column,
            district_type_column,
            "school_district_missing"
        ]
    ].head()
)


# Remove temporary identifier if it is no longer needed
df_engineered = df_engineered.drop(
    columns="_row_id"
)


# --------------------------------------------------
# 9. Save the enriched dataset
# --------------------------------------------------

output_file = (
    folder / "residential_with_school_districts.csv"
)

df_engineered.to_csv(
    output_file,
    index=False
)

School district shape: (936, 51)
Original CRS: EPSG:3857
Columns: ['OBJECTID', 'Year', 'FedID', 'CDCode', 'CDSCode', 'CountyName', 'DistrictName', 'DistrictType', 'GradeLow', 'GradeHigh', 'GradeLowCensus', 'GradeHighCensus', 'AssistStatus', 'UpdateNotes', 'EnrollTotal', 'EnrollCharter', 'EnrollNonCharter', 'AAcount', 'AApct', 'AIcount', 'AIpct', 'AScount', 'ASpct', 'FIcount', 'FIpct', 'HIcount', 'HIpct', 'PIcount', 'PIpct', 'WHcount', 'WHpct', 'MRcount', 'MRpct', 'NRcount', 'NRpct', 'ELcount', 'ELpct', 'FOScount', 'FOSpct', 'HOMcount', 'HOMpct', 'MIGcount', 'MIGpct', 'SWDcount', 'SWDpct', 'SEDcount', 'SEDpct', 'DistrctAreaSqMi', 'LocaleCode', 'LocaleDesc', 'geometry']
DistrictType
Elementary    515
Unified       345
High           76
Name: count, dtype: int64
Unified district polygons: 345
            DistrictName DistrictType
0        Alameda Unified      Unified
1    Albany City Unified      Unified
2       Berkeley Unified      Unified
3  Castro Valley Unified      Unified
4          Emery Unified      Unified
Properties with valid California coordinates: 142339
Properties with invalid or missing coordinates: 45
    Latitude   Longitude
0  34.264692 -117.221040
1  34.107983 -118.390320
2  37.567434 -122.388226
3  33.906058 -117.777782
4  37.705919 -122.059421
Property CRS: EPSG:4326
District CRS: EPSG:4326

C:\Users\luoxu\AppData\Local\Temp\ipykernel_23996\948470939.py:255: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_engineered = pd.concat(

Overall school district match rate: 75.77%
Match rate among valid coordinates: 75.79%
    Latitude   Longitude                   DistrictName DistrictType  \
0  34.264692 -117.221040       Rim of the World Unified      Unified
1  34.107983 -118.390320            Los Angeles Unified      Unified
2  37.567434 -122.388226                            NaN         <NA>
3  33.906058 -117.777782  Placentia-Yorba Linda Unified      Unified
4  37.705919 -122.059421          Castro Valley Unified      Unified

   school_district_missing
0                        0
1                        0
2                        1
3                        0
4                        0

In [17]:
# numeric for district 
district_dummies = pd.get_dummies(
    df_engineered[
        [
            district_name_column,
            district_type_column
        ]
    ],
    prefix=[
        "school_district",
        "school_district_type"
    ],
    drop_first=True,
    dtype=int
)

df_engineered = pd.concat(
    [
        df_engineered.drop(
            columns=[
                district_name_column,
                district_type_column
            ]
        ),
        district_dummies
    ],
    axis=1
)

non_numeric_columns = (
    df_engineered
    .select_dtypes(
        exclude=np.number
    )
    .columns
    .tolist()
)

print("Non-numeric columns:", non_numeric_columns)

protected_columns = [
    target,
    "source_month"
]

remaining_text_columns = [
    column
    for column in non_numeric_columns
    if column not in protected_columns
]

df_engineered = df_engineered.drop(
    columns=remaining_text_columns,
    errors="ignore"
)

Non-numeric columns: ['source_month', 'City_Corona', 'City_Escondido', 'City_Fontana', 'City_Hemet', 'City_Hesperia', 'City_Huntington Beach', 'City_Indio', 'City_La Quinta', 'City_Lancaster', 'City_Long Beach', 'City_Los Angeles', 'City_Menifee', 'City_Moreno Valley', 'City_Murrieta', 'City_Oakland', 'City_Oceanside', 'City_Other', 'City_Palm Desert', 'City_Palmdale', 'City_Riverside', 'City_San Bernardino', 'City_San Diego', 'City_San Jose', 'City_Temecula', 'City_Victorville', 'CountyOrParish_Butte', 'CountyOrParish_Contra Costa', 'CountyOrParish_Fresno', 'CountyOrParish_Kern', 'CountyOrParish_Lake', 'CountyOrParish_Los Angeles', 'CountyOrParish_Madera', 'CountyOrParish_Merced', 'CountyOrParish_Monterey', 'CountyOrParish_Orange', 'CountyOrParish_Other', 'CountyOrParish_Riverside', 'CountyOrParish_Sacramento', 'CountyOrParish_San Benito', 'CountyOrParish_San Bernardino', 'CountyOrParish_San Diego', 'CountyOrParish_San Joaquin', 'CountyOrParish_San Luis Obispo', 'CountyOrParish_San Mateo', 'CountyOrParish_Santa Barbara', 'CountyOrParish_Santa Clara', 'CountyOrParish_Santa Cruz', 'CountyOrParish_Solano', 'CountyOrParish_Stanislaus', 'CountyOrParish_Ventura', 'MLSAreaMajor_251 - Jurupa Valley', 'MLSAreaMajor_252 - Riverside', 'MLSAreaMajor_259 - Moreno Valley', 'MLSAreaMajor_263 - Banning/Beaumont/Cherry Valley', 'MLSAreaMajor_264 - Fontana', 'MLSAreaMajor_268 - Redlands', 'MLSAreaMajor_269 - Yucaipa/Calimesa/Oak Glen', 'MLSAreaMajor_274 - San Bernardino', 'MLSAreaMajor_313 - La Quinta South of HWY 111', 'MLSAreaMajor_670 - Whittier', 'MLSAreaMajor_686 - Ontario', 'MLSAreaMajor_688 - Rancho Cucamonga', 'MLSAreaMajor_699 - Not Defined', 'MLSAreaMajor_83 - Fullerton', 'MLSAreaMajor_92028 - Fallbrook', 'MLSAreaMajor_APPV - Apple Valley', 'MLSAreaMajor_BKSF - Bakersfield', 'MLSAreaMajor_HSP - Hesperia', 'MLSAreaMajor_LAC - Lancaster', 'MLSAreaMajor_Other', 'MLSAreaMajor_PLM - Palmdale', 'MLSAreaMajor_SRCAR - Southwest Riverside County', 'MLSAreaMajor_Unknown', 'MLSAreaMajor_VIC - Victorville', 'MLSAreaMajor_WHLL - Woodland Hills', 'SubdivisionName_Arrowhead Woods (AWHW)', 'SubdivisionName_Chula Vista', 'SubdivisionName_Clairemont', 'SubdivisionName_El Cajon', 'SubdivisionName_Fallbrook', 'SubdivisionName_La Jolla', 'SubdivisionName_La Mesa', 'SubdivisionName_North Escondido', 'SubdivisionName_Not Applicable-1', 'SubdivisionName_Not Listed', 'SubdivisionName_Oceanside', 'SubdivisionName_Other', 'SubdivisionName_Out Of Area', 'SubdivisionName_Poway', 'SubdivisionName_Rancho Bernardo', 'SubdivisionName_Rancho Penasquitos', 'SubdivisionName_San Diego', 'SubdivisionName_San Luis Obispo(380)', 'SubdivisionName_Santee', 'SubdivisionName_Spring Valley', 'SubdivisionName_Sun City', 'SubdivisionName_Sun City Shadow Hills (30921)', 'SubdivisionName_Unknown', 'SubdivisionName_other', 'HighSchoolDistrict_Apple Valley Unified', 'HighSchoolDistrict_Capistrano Unified', 'HighSchoolDistrict_Corona-Norco Unified', 'HighSchoolDistrict_Hemet Unified', 'HighSchoolDistrict_Hesperia Unified', 'HighSchoolDistrict_Huntington Beach Union High', 'HighSchoolDistrict_Lake Elsinore Unified', 'HighSchoolDistrict_Long Beach Unified', 'HighSchoolDistrict_Los Angeles Unified', 'HighSchoolDistrict_Menifee Union', 'HighSchoolDistrict_Moreno Valley Unified', 'HighSchoolDistrict_Murrieta', 'HighSchoolDistrict_Newport Mesa Unified', 'HighSchoolDistrict_Orange Unified', 'HighSchoolDistrict_Other', 'HighSchoolDistrict_Perris Union High', 'HighSchoolDistrict_Rim of the World', 'HighSchoolDistrict_Riverside Unified', 'HighSchoolDistrict_Saddleback Valley Unified', 'HighSchoolDistrict_San Bernardino City Unified', 'HighSchoolDistrict_San Diego Unified', 'HighSchoolDistrict_Temecula Unified', 'HighSchoolDistrict_Unknown', 'HighSchoolDistrict_William S. Hart Union', 'Levels_MultiSplit,One', 'Levels_One', 'Levels_One,MultiSplit', 'Levels_One,ThreeOrMore', 'Levels_One,Two', 'Levels_One,Two,MultiSplit', 'Levels_One,Two,ThreeOrMore', 'Levels_One,Two,ThreeOrMore,MultiSplit', 'Levels_ThreeOrMore', 'Levels_ThreeOrMore,MultiSplit', 'Levels_ThreeOrMore,One', 'Levels_Two', 'Levels_Two,MultiSplit', 'Levels_Two,MultiSplit,One', 'Levels_Two,One', 'Levels_Two,ThreeOrMore', 'Levels_Two,ThreeOrMore,MultiSplit', 'Levels_Unknown', 'PostalCode_92201', 'PostalCode_92203', 'PostalCode_92211', 'PostalCode_92220', 'PostalCode_92223', 'PostalCode_92253', 'PostalCode_92262', 'PostalCode_92270', 'PostalCode_92307', 'PostalCode_92308', 'PostalCode_92336', 'PostalCode_92345', 'PostalCode_92530', 'PostalCode_92562', 'PostalCode_92563', 'PostalCode_92584', 'PostalCode_92592', 'PostalCode_92596', 'PostalCode_93065', 'PostalCode_93446', 'PostalCode_93535', 'PostalCode_93536', 'PostalCode_93551', 'PostalCode_94513', 'PostalCode_Other']

In [18]:
df_engineered

,ClosePrice,source_month,LivingArea,DaysOnMarket,LotSizeSquareFeet,YearBuilt,BathroomsTotalInteger,BedroomsTotal,GarageSpaces,Latitude,...,school_district_Williams Unified,school_district_Willits Unified,school_district_Willows Unified,school_district_Windsor Unified,school_district_Wiseburn Unified,school_district_Woodlake Unified,school_district_Woodland Joint Unified,school_district_Yosemite Unified,school_district_Yuba City Unified,school_district_Yucaipa-Calimesa Joint Unified
0,890000.0,202506,3000.0,181,9600.0,2021.0,3.0,3.0,2.0,34.264692,...,0,0,0,0,0,0,0,0,0,0
1,1876384.0,202506,1800.0,87,10400.0,1963.0,3.0,3.0,2.0,34.107983,...,0,0,0,0,0,0,0,0,0,0
2,4820000.0,202506,4270.0,0,22505.0,1980.0,6.0,6.0,3.0,37.567434,...,0,0,0,0,0,0,0,0,0,0
3,865000.0,202506,1442.0,0,4800.0,1985.0,2.0,3.0,2.0,33.906058,...,0,0,0,0,0,0,0,0,0,0
4,875000.0,202506,1086.0,0,5500.0,1953.0,1.0,3.0,4.0,37.705919,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142379,40000.0,202606,1274.0,597,5100.0,1972.0,1.0,2.0,0.0,34.820415,...,0,0,0,0,0,0,0,0,0,0
142380,865000.0,202606,2166.0,674,868586.4,1975.0,3.0,5.0,2.0,34.242304,...,0,0,0,0,0,0,0,0,0,0
142381,280000.0,202606,2034.0,704,11433.0,2025.0,2.0,3.0,2.0,37.846557,...,0,0,0,0,0,0,0,0,0,0
142382,595000.0,202606,2502.0,961,4389.0,1890.0,3.0,4.0,1.0,37.824500,...,0,0,0,0,0,0,0,0,0,0
142383,3000000.0,202606,1473.0,1553,106836562.8,1948.0,2.0,3.0,1.0,35.633015,...,0,0,0,0,0,0,0,0,0,0

In [25]:
output_file = (
    folder / "engineered.csv"
)

df_engineered.to_csv(
    output_file,
    index=False
)

In [24]:
df_engineered.columns.tolist()

['ClosePrice',
 'source_month',
 'LivingArea',
 'DaysOnMarket',
 'LotSizeSquareFeet',
 'YearBuilt',
 'BathroomsTotalInteger',
 'BedroomsTotal',
 'GarageSpaces',
 'Latitude',
 'Longitude',
 'AssociationFee',
 'Stories',
 'MainLevelBedrooms',
 'PoolPrivateYN',
 'FireplaceYN',
 'NewConstructionYN',
 'AttachedGarageYN',
 'ViewYN',
 'LivingArea_missing_flag',
 'DaysOnMarket_missing_flag',
 'LotSizeSquareFeet_missing_flag',
 'YearBuilt_missing_flag',
 'BathroomsTotalInteger_missing_flag',
 'BedroomsTotal_missing_flag',
 'GarageSpaces_missing_flag',
 'Latitude_missing_flag',
 'Longitude_missing_flag',
 'AssociationFee_missing_flag',
 'Stories_missing_flag',
 'MainLevelBedrooms_missing_flag',
 'PoolPrivateYN_missing_flag',
 'FireplaceYN_missing_flag',
 'NewConstructionYN_missing_flag',
 'AttachedGarageYN_missing_flag',
 'ViewYN_missing_flag',
 'sale_year',
 'sale_month_number',
 'sale_quarter',
 'month_sin',
 'month_cos',
 'property_age',
 'property_age_squared',
 'is_new_property',
 'is_old_property',
 'bed_bath_ratio',
 'bath_bed_ratio',
 'total_bed_bath',
 'bed_bath_difference',
 'more_bathrooms_than_bedrooms',
 'living_area_squared',
 'log_living_area',
 'small_home_flag',
 'large_home_flag',
 'living_area_per_bedroom',
 'living_area_per_bathroom',
 'log_lot_size',
 'large_lot_flag',
 'small_lot_flag',
 'lot_to_living_ratio',
 'building_coverage_ratio',
 'unused_lot_area',
 'single_story_flag',
 'multi_story_flag',
 'LivingArea_missing',
 'LotSizeSquareFeet_missing',
 'YearBuilt_missing',
 'BedroomsTotal_missing',
 'BathroomsTotalInteger_missing',
 'AssociationFee_missing',
 'Stories_missing',
 'MainLevelBedrooms_missing',
 'missing_feature_count',
 'school_district_missing',
 'school_district_Acton-Agua Dulce Unified',
 'school_district_Alameda Unified',
 'school_district_Albany City Unified',
 'school_district_Alhambra Unified',
 'school_district_Alpaugh Unified',
 'school_district_Alvord Unified',
 'school_district_Amador County Unified',
 'school_district_Anderson Valley Unified',
 'school_district_Antioch Unified',
 'school_district_Apple Valley Unified',
 'school_district_Arcadia Unified',
 'school_district_Aromas - San Juan Unified',
 'school_district_Atascadero Unified',
 'school_district_Azusa Unified',
 'school_district_Baldwin Park Unified',
 'school_district_Banning Unified',
 'school_district_Banta Unified',
 'school_district_Barstow Unified',
 'school_district_Bassett Unified',
 'school_district_Bear Valley Unified',
 'school_district_Beaumont Unified',
 'school_district_Bellflower Unified',
 'school_district_Benicia Unified',
 'school_district_Berkeley Unified',
 'school_district_Beverly Hills Unified',
 'school_district_Big Oak Flat-Groveland Unified',
 'school_district_Biggs Unified',
 'school_district_Bishop Unified',
 'school_district_Black Oak Mine Unified',
 'school_district_Bonita Unified',
 'school_district_Bonsall Unified',
 'school_district_Borrego Springs Unified',
 'school_district_Brea-Olinda Unified',
 'school_district_Burbank Unified',
 'school_district_Cabrillo Unified',
 'school_district_Calaveras Unified',
 'school_district_Calexico Unified',
 'school_district_Calipatria Unified',
 'school_district_Calistoga Joint Unified',
 'school_district_Capistrano Unified',
 'school_district_Carlsbad Unified',
 'school_district_Carmel Unified',
 'school_district_Carpinteria Unified',
 'school_district_Caruthers Unified',
 'school_district_Castro Valley Unified',
 'school_district_Center Joint Unified',
 'school_district_Central Unified',
 'school_district_Ceres Unified',
 'school_district_Charter Oak Unified',
 'school_district_Chawanakee Unified',
 'school_district_Chico Unified',
 'school_district_Chino Valley Unified',
 'school_district_Claremont Unified',
 'school_district_Cloverdale Unified',
 'school_district_Clovis Unified',
 'school_district_Coachella Valley Unified',
 'school_district_Coalinga-Huron Unified',
 'school_district_Coast Unified',
 'school_district_Colton Joint Unified',
 'school_district_Colusa Unified',
 'school_district_Compton Unified',
 'school_district_Conejo Valley Unified',
 'school_district_Corcoran Joint Unified',
 'school_district_Corona-Norco Unified',
 'school_district_Coronado Unified',
 'school_district_Cotati-Rohnert Park Unified',
 'school_district_Covina-Valley Unified',
 'school_district_Culver City Unified',
 'school_district_Cutler-Orosi Joint Unified',
 'school_district_Cuyama Joint Unified',
 'school_district_Davis Joint Unified',
 'school_district_Delhi Unified',
 'school_district_Denair Unified',
 'school_district_Desert Center Unified',
 'school_district_Desert Sands Unified',
 'school_district_Dinuba Unified',
 'school_district_Dixon Unified',
 'school_district_Dos Palos Oro Loma Joint Unified',
 'school_district_Downey Unified',
 'school_district_Duarte Unified',
 'school_district_Dublin Unified',
 'school_district_Durham Unified',
 'school_district_Eastern Sierra Unified',
 'school_district_El Rancho Unified',
 'school_district_El Segundo Unified',
 'school_district_El Tejon Unified',
 'school_district_Elk Grove Unified',
 'school_district_Emery Unified',
 'school_district_Escalon Unified',
 'school_district_Esparto Unified',
 'school_district_Eureka City Schools',
 'school_district_Exeter Unified',
 'school_district_Fairfield-Suisun Unified',
 'school_district_Farmersville Unified',
 'school_district_Fillmore Unified',
 'school_district_Firebaugh-Las Deltas Unified',
 'school_district_Folsom-Cordova Unified',
 'school_district_Fontana Unified',
 'school_district_Fort Bragg Unified',
 'school_district_Fowler Unified',
 'school_district_Fremont Unified',
 'school_district_Fresno Unified',
 'school_district_Garden Grove Unified',
 'school_district_Gateway Unified',
 'school_district_Gilroy Unified',
 'school_district_Glendale Unified',
 'school_district_Glendora Unified',
 'school_district_Golden Plains Unified',
 'school_district_Golden Valley Unified',
 'school_district_Gonzales Unified',
 'school_district_Gridley Unified',
 'school_district_Gustine Unified',
 'school_district_Hacienda la Puente Unified',
 'school_district_Hamilton Unified',
 'school_district_Hayward Unified',
 'school_district_Healdsburg Unified',
 'school_district_Hemet Unified',
 'school_district_Hesperia Unified',
 'school_district_Hilmar Unified',
 'school_district_Holtville Unified',
 'school_district_Hughson Unified',
 'school_district_Imperial Unified',
 'school_district_Inglewood Unified',
 'school_district_Irvine Unified',
 'school_district_John Swett Unified',
 'school_district_Jurupa Unified',
 'school_district_Kelseyville Unified',
 'school_district_Kerman Unified',
 'school_district_Kings Canyon Joint Unified',
 'school_district_Konocti Unified',
 'school_district_La Canada Unified',
 'school_district_La Honda-Pescadero Unified',
 'school_district_Laguna Beach Unified',
 'school_district_Lake Elsinore Unified',
 'school_district_Lake Tahoe Unified',
 'school_district_Lakeport Unified',
 'school_district_Lammersville Joint Unified',
 'school_district_Las Virgenes Unified',
 'school_district_Laytonville Unified',
 'school_district_Lincoln Unified',
 'school_district_Linden Unified',
 'school_district_Lindsay Unified',
 'school_district_Live Oak Unified',
 'school_district_Livermore Valley Joint Unified',
 'school_district_Lodi Unified',
 'school_district_Lompoc Unified',
 'school_district_Lone Pine Unified',
 'school_district_Long Beach Unified',
 'school_district_Los Alamitos Unified',
 'school_district_Los Angeles Unified',
 'school_district_Los Banos Unified',
 'school_district_Los Molinos Unified',
 'school_district_Lucerne Valley Unified',
 'school_district_Lucia Mar Unified',
 'school_district_Lynwood Unified',
 'school_district_Madera Unified',
 'school_district_Mammoth Unified',
 'school_district_Manhattan Beach Unified',
 'school_district_Manteca Unified',
 'school_district_Maricopa Unified',
 'school_district_Mariposa County Unified',
 'school_district_Martinez Unified',
 'school_district_Marysville Joint Unified',
 'school_district_Maxwell Unified',
 'school_district_McFarland Unified',
 'school_district_Mendocino Unified',
 'school_district_Middletown Unified',
 'school_district_Milpitas Unified',
 'school_district_Modoc Joint Unified',
 'school_district_Mojave Unified',
 'school_district_Monrovia Unified',
 'school_district_Montebello Unified',
 'school_district_Monterey Peninsula Unified',
 'school_district_Moorpark Unified',
 'school_district_Moreno Valley Unified',
 'school_district_Morgan Hill Unified',
 'school_district_Morongo Unified',
 'school_district_Mountain Empire Unified',
 'school_district_Mountain Valley Unified',
 'school_district_Mt. Diablo Unified',
 'school_district_Muroc Joint Unified',
 'school_district_Murrieta Valley Unified',
 'school_district_Napa Valley Unified',
 'school_district_Natomas Unified',
 'school_district_Needles Unified',
 'school_district_New Haven Unified',
 'school_district_Newark Unified',
 'school_district_Newman-Crows Landing Unified',
 'school_district_Newport-Mesa Unified',
 'school_district_North Monterey County Unified',
 'school_district_Norwalk-La Mirada Unified',
 'school_district_Novato Unified',
 'school_district_Oak Park Unified',
 'school_district_Oakdale Joint Unified',
 'school_district_Oakland Unified',
 'school_district_Oceanside Unified',
 'school_district_Ojai Unified',
 'school_district_Orange Unified',
 'school_district_Orland Joint Unified',
 'school_district_Pacific Grove Unified',
 'school_district_Pajaro Valley Unified',
 'school_district_Palm Springs Unified',
 'school_district_Palo Alto Unified',
 'school_district_Palo Verde Unified',
 'school_district_Palos Verdes Peninsula Unified',
 'school_district_Paradise Unified',
 'school_district_Paramount Unified',
 'school_district_Parlier Unified',
 'school_district_Pasadena Unified',
 'school_district_Paso Robles Joint Unified',
 'school_district_Patterson Joint Unified',
 'school_district_Piedmont City Unified',
 'school_district_Pierce Joint Unified',
 'school_district_Pittsburg Unified',
 'school_district_Placentia-Yorba Linda Unified',
 'school_district_Pleasanton Unified',
 'school_district_Plumas Unified',
 'school_district_Pomona Unified',
 'school_district_Porterville Unified',
 'school_district_Potter Valley Community Unified',
 'school_district_Poway Unified',
 'school_district_Princeton Joint Unified',
 'school_district_Ramona City Unified',
 'school_district_Redlands Unified',
 'school_district_Redondo Beach Unified',
 'school_district_Reef-Sunset Unified',
 'school_district_Rialto Unified',
 'school_district_Rim of the World Unified',
 'school_district_Ripon Unified',
 'school_district_River Delta Joint Unified',
 'school_district_Riverbank Unified',
 'school_district_Riverdale Joint Unified',
 'school_district_Riverside Unified',
 'school_district_Rocklin Unified',
 'school_district_Round Valley Unified',
 'school_district_Rowland Unified',
 'school_district_Sacramento City Unified',
 'school_district_Saddleback Valley Unified',
 'school_district_Saint Helena Unified',
 'school_district_San Bernardino City Unified',
 'school_district_San Diego Unified',
 'school_district_San Francisco Unified',
 'school_district_San Gabriel Unified',
 'school_district_San Jacinto Unified',
 'school_district_San Jose Unified',
 'school_district_San Juan Unified',
 'school_district_San Leandro Unified',
 'school_district_San Lorenzo Unified',
 'school_district_San Lorenzo Valley Unified',
 'school_district_San Luis Coastal Unified',
 'school_district_San Marcos Unified',
 'school_district_San Marino Unified',
 'school_district_San Ramon Valley Unified',
 'school_district_Sanger Unified',
 'school_district_Santa Ana Unified',
 'school_district_Santa Barbara Unified',
 'school_district_Santa Clara Unified',
 'school_district_Santa Monica-Malibu Unified',
 'school_district_Santa Paula Unified',
 'school_district_Scott Valley Unified',
 'school_district_Scotts Valley Unified',
 'school_district_Selma Unified',
 'school_district_Shandon Joint Unified',
 'school_district_Shoreline Unified',
 'school_district_Sierra Sands Unified',
 'school_district_Sierra Unified',
 'school_district_Sierra-Plumas Joint Unified',
 'school_district_Silver Valley Unified',
 'school_district_Simi Valley Unified',
 'school_district_Snowline Joint Unified',
 'school_district_Soledad Unified',
 'school_district_Sonoma Valley Unified',
 'school_district_South Pasadena Unified',
 'school_district_South San Francisco Unified',
 'school_district_Southern Humboldt Joint Unified',
 'school_district_Southern Kern Unified',
 'school_district_Stockton Unified',
 'school_district_Stony Creek Joint Unified',
 'school_district_Sunol Glen Unified',
 'school_district_Tahoe-Truckee Unified',
 'school_district_Tehachapi Unified',
 'school_district_Temecula Valley Unified',
 'school_district_Temple City Unified',
 'school_district_Templeton Unified',
 'school_district_Torrance Unified',
 'school_district_Tracy Joint Unified',
 'school_district_Travis Unified',
 'school_district_Trinity Alps Unified',
 'school_district_Trona Joint Unified',
 'school_district_Turlock Unified',
 'school_district_Tustin Unified',
 'school_district_Twin Rivers Unified',
 'school_district_Ukiah Unified',
 'school_district_Upland Unified',
 'school_district_Upper Lake Unified',
 'school_district_Vacaville Unified',
 'school_district_Val Verde Unified',
 'school_district_Vallejo City Unified',
 'school_district_Valley Center-Pauma Unified',
 'school_district_Ventura Unified',
 'school_district_Visalia Unified',
 'school_district_Vista Unified',
 'school_district_Walnut Valley Unified',
 'school_district_Warner Unified',
 'school_district_Washington Unified',
 'school_district_Waterford Unified',
 'school_district_West Contra Costa Unified',
 'school_district_West Covina Unified',
 'school_district_Western Placer Unified',
 'school_district_Westwood Unified',
 'school_district_Williams Unified',
 'school_district_Willits Unified',
 'school_district_Willows Unified',
 'school_district_Windsor Unified',
 'school_district_Wiseburn Unified',
 'school_district_Woodlake Unified',
 'school_district_Woodland Joint Unified',
 'school_district_Yosemite Unified',
 'school_district_Yuba City Unified',
 'school_district_Yucaipa-Calimesa Joint Unified']

In [19]:
# new vs old feature count

drop_cols = [
    target,
    "source_month"
]

old_feature_cols = [
    column
    for column in df.columns
    if column not in drop_cols
]

new_feature_cols = [
    column
    for column in df_engineered.columns
    if column not in drop_cols
]

print(
    "Old feature count:",
    len(old_feature_cols)
)

print(
    "New feature count:",
    len(new_feature_cols)
)

Old feature count: 200
New feature count: 392

In [20]:
models = {
    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )
}

In [21]:
def evaluate_models(
    data,
    feature_cols,
    feature_set_name
):

    model_results = []

    months = sorted(
        data["source_month"].unique()
    )

    for X_window in [3, 6, 9, 12]:

        train_months = months[
            -(X_window + 1):-1
        ]

        test_month = months[-1]

        train_df = data[
            data["source_month"].isin(
                train_months
            )
        ].copy()

        test_df = data[
            data["source_month"]
            == test_month
        ].copy()

        X_train = train_df[feature_cols]
        y_train = train_df[target]

        X_test = test_df[feature_cols]
        y_test = test_df[target]

        for model_name, model in models.items():

            model.fit(
                X_train,
                y_train
            )

            train_preds = model.predict(
                X_train
            )

            test_preds = model.predict(
                X_test
            )

            train_r2 = r2_score(
                y_train,
                train_preds
            )

            test_r2 = r2_score(
                y_test,
                test_preds
            )

            mae = mean_absolute_error(
                y_test,
                test_preds
            )

            rmse = np.sqrt(
                mean_squared_error(
                    y_test,
                    test_preds
                )
            )

            model_results.append({
                "feature_set": feature_set_name,
                "model": model_name,
                "training_window_months": X_window,
                "train_months": ", ".join(
                    train_months
                ),
                "test_month": test_month,
                "feature_count": len(
                    feature_cols
                ),
                "train_r2": train_r2,
                "test_r2": test_r2,
                "mae": mae,
                "rmse": rmse
            })

    return pd.DataFrame(
        model_results
    )

In [22]:
old_results = evaluate_models(
    data=df,
    feature_cols=old_feature_cols,
    feature_set_name="Old feature set"
)

old_results.sort_values(
    by="test_r2",
    ascending=False
)

KeyboardInterrupt:

In [ ]:
new_results = evaluate_models(
    data=df_engineered,
    feature_cols=new_feature_cols,
    feature_set_name=(
        "Engineered features "
        "+ school district"
    )
)

new_results.sort_values(
    by="test_r2",
    ascending=False
)

,feature_set,model,training_window_months,train_months,test_month,feature_count,train_r2,test_r2,mae,rmse
9,Engineered features + school district,Linear Regression,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,0.016734,0.477487,558305.167281,1.110699e+06
6,Engineered features + school district,Linear Regression,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,0.011350,0.457700,562460.188444,1.131535e+06
3,Engineered features + school district,Linear Regression,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,0.018927,0.448763,556826.786945,1.140820e+06
0,Engineered features + school district,Linear Regression,3,"202603, 202604, 202605",202606,392,0.022170,0.325517,574425.397679,1.261925e+06
2,Engineered features + school district,Random Forest,3,"202603, 202604, 202605",202606,392,0.834906,-4.913348,343151.898168,3.736499e+06
11,Engineered features + school district,Random Forest,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,0.838875,-4.972378,310260.767652,3.755102e+06
5,Engineered features + school district,Random Forest,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,0.818118,-6.036501,308488.462793,4.075928e+06
8,Engineered features + school district,Random Forest,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,0.834901,-6.243786,331506.364399,4.135528e+06
4,Engineered features + school district,Decision Tree,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,1.000000,-13.225589,384266.590460,5.795398e+06
1,Engineered features + school district,Decision Tree,3,"202603, 202604, 202605",202606,392,1.000000,-13.560441,406046.222705,5.863209e+06
10,Engineered features + school district,Decision Tree,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,1.000000,-25.392849,396781.321264,7.893893e+06
7,Engineered features + school district,Decision Tree,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,1.000000,-55.977270,491420.405586,1.159842e+07

In [ ]:
feature_comparison_df = pd.concat(
    [
        old_results,
        new_results
    ],
    ignore_index=True
)

feature_comparison_df.sort_values(
    by="test_r2",
    ascending=False
)

,feature_set,model,training_window_months,train_months,test_month,feature_count,train_r2,test_r2,mae,rmse
21,Engineered features + school district,Linear Regression,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,0.016734,0.477487,558305.167281,1.110699e+06
9,Old feature set,Linear Regression,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,200,0.014958,0.472322,572191.011960,1.116176e+06
3,Old feature set,Linear Regression,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,200,0.015931,0.468593,556753.222951,1.120113e+06
0,Old feature set,Linear Regression,3,"202603, 202604, 202605",202606,200,0.014623,0.468579,566923.592680,1.120128e+06
6,Old feature set,Linear Regression,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,200,0.009956,0.465947,560517.607724,1.122899e+06
18,Engineered features + school district,Linear Regression,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,0.011350,0.457700,562460.188444,1.131535e+06
15,Engineered features + school district,Linear Regression,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,0.018927,0.448763,556826.786945,1.140820e+06
12,Engineered features + school district,Linear Regression,3,"202603, 202604, 202605",202606,392,0.022170,0.325517,574425.397679,1.261925e+06
14,Engineered features + school district,Random Forest,3,"202603, 202604, 202605",202606,392,0.834906,-4.913348,343151.898168,3.736499e+06
23,Engineered features + school district,Random Forest,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,0.838875,-4.972378,310260.767652,3.755102e+06
17,Engineered features + school district,Random Forest,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,0.818118,-6.036501,308488.462793,4.075928e+06
20,Engineered features + school district,Random Forest,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,0.834901,-6.243786,331506.364399,4.135528e+06
11,Old feature set,Random Forest,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,200,0.841250,-6.433140,352407.493405,4.189231e+06
5,Old feature set,Random Forest,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,200,0.826959,-9.470706,351271.454259,4.972057e+06
2,Old feature set,Random Forest,3,"202603, 202604, 202605",202606,200,0.843456,-9.525622,381037.588263,4.985079e+06
16,Engineered features + school district,Decision Tree,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,1.000000,-13.225589,384266.590460,5.795398e+06
13,Engineered features + school district,Decision Tree,3,"202603, 202604, 202605",202606,392,1.000000,-13.560441,406046.222705,5.863209e+06
8,Old feature set,Random Forest,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,200,0.835601,-15.224120,435740.536669,6.189117e+06
10,Old feature set,Decision Tree,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,200,0.999988,-18.097696,364507.844717,6.714886e+06
22,Engineered features + school district,Decision Tree,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,1.000000,-25.392849,396781.321264,7.893893e+06
1,Old feature set,Decision Tree,3,"202603, 202604, 202605",202606,200,1.000000,-32.807832,465317.242103,8.934223e+06
7,Old feature set,Decision Tree,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,200,0.999986,-37.532127,424544.209418,9.538051e+06
4,Old feature set,Decision Tree,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,200,0.999968,-53.937929,504810.377430,1.138897e+07
19,Engineered features + school district,Decision Tree,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,1.000000,-55.977270,491420.405586,1.159842e+07

In [ ]:
feature_comparison_df = pd.concat(
    [
        old_results,
        new_results
    ],
    ignore_index=True
)

feature_comparison_df.sort_values(
    by="test_r2",
    ascending=False
)

,feature_set,model,training_window_months,train_months,test_month,feature_count,train_r2,test_r2,mae,rmse
21,Engineered features + school district,Linear Regression,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,0.016734,0.477487,558305.167281,1.110699e+06
9,Old feature set,Linear Regression,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,200,0.014958,0.472322,572191.011960,1.116176e+06
3,Old feature set,Linear Regression,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,200,0.015931,0.468593,556753.222951,1.120113e+06
0,Old feature set,Linear Regression,3,"202603, 202604, 202605",202606,200,0.014623,0.468579,566923.592680,1.120128e+06
6,Old feature set,Linear Regression,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,200,0.009956,0.465947,560517.607724,1.122899e+06
18,Engineered features + school district,Linear Regression,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,0.011350,0.457700,562460.188444,1.131535e+06
15,Engineered features + school district,Linear Regression,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,0.018927,0.448763,556826.786945,1.140820e+06
12,Engineered features + school district,Linear Regression,3,"202603, 202604, 202605",202606,392,0.022170,0.325517,574425.397679,1.261925e+06
14,Engineered features + school district,Random Forest,3,"202603, 202604, 202605",202606,392,0.834906,-4.913348,343151.898168,3.736499e+06
23,Engineered features + school district,Random Forest,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,0.838875,-4.972378,310260.767652,3.755102e+06
17,Engineered features + school district,Random Forest,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,0.818118,-6.036501,308488.462793,4.075928e+06
20,Engineered features + school district,Random Forest,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,0.834901,-6.243786,331506.364399,4.135528e+06
11,Old feature set,Random Forest,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,200,0.841250,-6.433140,352407.493405,4.189231e+06
5,Old feature set,Random Forest,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,200,0.826959,-9.470706,351271.454259,4.972057e+06
2,Old feature set,Random Forest,3,"202603, 202604, 202605",202606,200,0.843456,-9.525622,381037.588263,4.985079e+06
16,Engineered features + school district,Decision Tree,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,392,1.000000,-13.225589,384266.590460,5.795398e+06
13,Engineered features + school district,Decision Tree,3,"202603, 202604, 202605",202606,392,1.000000,-13.560441,406046.222705,5.863209e+06
8,Old feature set,Random Forest,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,200,0.835601,-15.224120,435740.536669,6.189117e+06
10,Old feature set,Decision Tree,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,200,0.999988,-18.097696,364507.844717,6.714886e+06
22,Engineered features + school district,Decision Tree,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,392,1.000000,-25.392849,396781.321264,7.893893e+06
1,Old feature set,Decision Tree,3,"202603, 202604, 202605",202606,200,1.000000,-32.807832,465317.242103,8.934223e+06
7,Old feature set,Decision Tree,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,200,0.999986,-37.532127,424544.209418,9.538051e+06
4,Old feature set,Decision Tree,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,200,0.999968,-53.937929,504810.377430,1.138897e+07
19,Engineered features + school district,Decision Tree,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,392,1.000000,-55.977270,491420.405586,1.159842e+07

In [ ]:
r2_comparison_table = (
    feature_comparison_df
    .pivot_table(
        index=[
            "model",
            "training_window_months"
        ],
        columns="feature_set",
        values="test_r2"
    )
    .reset_index()
)

r2_comparison_table.columns.name = None

r2_comparison_table

,model,training_window_months,Engineered features + school district,Old feature set
0,Decision Tree,3,-13.560441,-32.807832
1,Decision Tree,6,-13.225589,-53.937929
2,Decision Tree,9,-55.977270,-37.532127
3,Decision Tree,12,-25.392849,-18.097696
4,Linear Regression,3,0.325517,0.468579
5,Linear Regression,6,0.448763,0.468593
6,Linear Regression,9,0.457700,0.465947
7,Linear Regression,12,0.477487,0.472322
8,Random Forest,3,-4.913348,-9.525622
9,Random Forest,6,-6.036501,-9.470706
10,Random Forest,9,-6.243786,-15.224120
11,Random Forest,12,-4.972378,-6.433140

In [ ]:
r2_comparison_table = (
    feature_comparison_df
    .pivot_table(
        index=[
            "model",
            "training_window_months"
        ],
        columns="feature_set",
        values="test_r2"
    )
    .reset_index()
)

r2_comparison_table.columns.name = None

r2_comparison_table

,model,training_window_months,Engineered features + school district,Old feature set
0,Decision Tree,3,-13.560441,-32.807832
1,Decision Tree,6,-13.225589,-53.937929
2,Decision Tree,9,-55.977270,-37.532127
3,Decision Tree,12,-25.392849,-18.097696
4,Linear Regression,3,0.325517,0.468579
5,Linear Regression,6,0.448763,0.468593
6,Linear Regression,9,0.457700,0.465947
7,Linear Regression,12,0.477487,0.472322
8,Random Forest,3,-4.913348,-9.525622
9,Random Forest,6,-6.036501,-9.470706
10,Random Forest,9,-6.243786,-15.224120
11,Random Forest,12,-4.972378,-6.433140

In [ ]:
best_baseline_row = (
    old_results[
        old_results["model"]
        == "Linear Regression"
    ]
    .sort_values(
        by="test_r2",
        ascending=False
    )
    .iloc[0]
)

best_baseline_r2 = (
    best_baseline_row["test_r2"]
)

best_baseline_window = (
    best_baseline_row[
        "training_window_months"
    ]
)

print(
    "Best baseline window:",
    best_baseline_window
)

print(
    f"Best baseline test R²: "
    f"{best_baseline_r2:.4f}"
)

Best baseline window: 12
Best baseline test R²: 0.4723

In [ ]:
# Sort models by highest test R²
comparison_df = comparison_df.sort_values(
    by="test_r2",
    ascending=False
).reset_index(drop=True)

# Save all model comparison results
output_file = folder / "model_comparison_results.csv"

comparison_df.to_csv(
    output_file,
    index=False
)

# Select the best overall model
best_model = comparison_df.iloc[0]

print("Best Model:", best_model["model"])
print(
    "Best training window:",
    best_model["training_window_months"],
    "months"
)
print("Training months:", best_model["train_months"])
print("Test month:", best_model["test_month"])
print(f"Training R²: {best_model['train_r2']:.4f}")
print(f"Test R²: {best_model['test_r2']:.4f}")
print(f"Test MAE: ${best_model['mae']:,.2f}")
print(f"Test RMSE: ${best_model['rmse']:,.2f}")

best_model_df = comparison_df.iloc[[0]]

best_model_file = folder / "best_model_result.csv"

best_model_df.to_csv(
    best_model_file,
    index=False
)

Best Model: Linear Regression
Best training window: 12 months
Training months: 202506, 202507, 202508, 202509, 202510, 202511, 202512, 202601, 202602, 202603, 202604, 202605
Test month: 202606
Training R²: 0.0150
Test R²: 0.4723
Test MAE: $572,191.01
Test RMSE: $1,116,175.51